project:
  type: website

website:
  title: "Oceanus Folk: Then & Now"
  navbar:
    left:
    - text: "Project Overview"
      href: "Project/Proposal.html"
    - text: "Prototype and Storyboard"
      href: "Project/XXX.html"
    - text: "Methodology and Analyis"
      href: "Project/Project.html"
    - text: "Poster"
      href: "Project/XXX.html"
    - text: "User Guide"
      href: "Project/XXX.html"
    Right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

