project:
  type: website

website:
  title: "<img src='/images/OceanusFolkIcon.png' alt='Home' style='height: 68px; width: 68px;'>"
  navbar:
    left:
    - text: "Overview"
      href: "Project/Proposal.html"
    - text: "Storyboard"
      href: "Project/PrototypeStoryboard.html"
    - text: "Prototype"
      menu:
        - text: "Data Pre-processing & Methodology"
          href: "Project/Project.html"
        - text: "Findings & Analysis"
          href: "Project/Analysis.html" 
    - text: "Shiny App"
      menu:
        - text: "Shiny App"
          href: "https://calvintansh.shinyapps.io/ISSS608-ProjectShiny/"
        - text: "User Guide"
          href: "Project/User_Guide.pdf"
    - text: "Poster"
      href: "Project/Poster.jpg"
    right:
      - text: Our Team
        href: "Project/about.html"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

render:
  - index.qmd


