project:
  type: website

website:
  navbar:
    logo: Images/OceanusFolk.png
    left:
    - text: "Project Overview"
      href: "Proposal/Proposal.html"
    - text: "Prototype and Storyboard"
      href: "Proposal/Proposal.html"
    
    Right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

