project:
  type: website

website:
  title: "ISSS608-VAAProject"
  navbar:
    left:
    - text: "Project Concept"
      href: "Proposal/Proposal.html"
    
    Right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

