---
title: "Project Proposal"
format: html
freeze: true
warning: false
date: "June 6, 2025"
---

# Motivation

The story of Sailor Shift is more than a tale of individual stardom — it is a reflection of how local culture, through music, can resonate on a global scale. Her rise from a small island nation to the forefront of the international music scene not only brought worldwide recognition to Oceanus Folk but also reshaped the genre itself. Sailor’s rising popularity led to greater interest in the genre’s roots, its collaborators, and its influence across musical styles.

This project is motivated by the opportunity to explore that transformation through data. By visualising the rich network of artistic relationships, genre influences, and temporal trends captured in a comprehensive knowledge graph, we aim to illustrate the pivotal role Sailor Shift has played as a prominent ambassador of Oceanus Folk. In collaboration with journalist Silas Reed, we seek to create meaningful visualisations that reveal the deeper story behind Sailor’s success, trace the evolution of Oceanus Folk, and uncover new and compelling insights along the way.

# Objectives

This project aims to build interactive visualisation tools that allow journalist Silas Reed and his readers to explore and uncover meaningful insights into Sailor Shift’s career and the influence of Oceanus Folk on the global music scene. The key objectives are as follows.

1.  **Understand the Profile of Sailor Shift’s Career**

    Visualisations will trace Sailor’s artistic journey, highlighting who has influenced her over time, her key collaborators, and the individuals she has directly or indirectly influenced. It will also explore how she has impacted members of the broader Oceanus Folk community.

2.  **Examine the Spread and Evolution of Oceanus Folk**

    The tools will map how Oceanus Folk has spread through the musical world by identifying whether its influence has been intermittent or gradual, pinpointing the most influenced genres and artists, and showing how the genre itself has evolved, especially through Sailor’s influence and cross-genre inspiration.

3.  **Develop a Profile of a Rising Star in the Music Industry**

    By visualising and comparing the career trajectories of three artists, the project will uncover key patterns in how an artist's influence evolve as he/she gains popularity. These patterns will then guide data-driven predictions about the next generation of Oceanus Folk artists expected to rise in the coming five years.

# Data

This project explores the data provided by [VAST Challenge 2025 Mini-Challenge 1](https://vast-challenge.github.io/2025/MC1.html). It is a comprehensive knowledge graph mapping the music industry's landscape which 17,412 nodes and 37,857 edges with 17 connected components.

Each node represents a person, song, record label, album or musical group. The edges represent the relationship between each pair of connected nodes as defined below.

| Edge Type | Source Node(s) | Destination Node(s) | Description |
|-----------------|-----------------|-----------------|----------------------|
| PerformerOf | Person, MusicalGroup | Song, Album | Source performed the destination. |
| ComposerOf | Person | Song, Album | Source composed the destination. |
| ProducerOf | Person, RecordLabel | Song, Album, Person, MusicalGroup | Source participated in the production of the destination's work. |
| LyricistOf | Person | Song, Album | Source wrote lyrics for the destination. |
| RecordedBy | Song, Album | RecordLabel | Destination aided in the recording process for the source. |
| DistributedBy | Song, Album | RecordLabel | Destination aided in the distribution process for the source. |
| InStyleOf | Song, Album | Song, Album, Person, MusicalGroup | Source was performed at least partly in the style of the destination. |
| InterpolatesFrom | Song, Album | Song, Album | Source interpolated a melody from the destination. |
| CoverOf | Song, Album | Song, Album | Source is a cover of the destination. |
| LyricalReferenceTo | Song, Album | Song, Album | Source makes a lyrical reference to the destination. |
| DirectlySamples | Song, Album | Song, Album | Source directly reuses a portion of the destination's audio via sampling. |
| MemberOf | Person | MusicalGroup | Source is (or was) a member of the destination. |

# Methodology

WIP

# Prototype Sketches

# R Packages

# Project Schedule
